name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  FS_PROJECT: BitBadger.Npgsql.FSharp.Documents
  CS_PROJECT: BitBadger.Npgsql.Documents

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        dotnet-version: [ "6.0", "7.0", "8.0" ]
        postgres-version: [ "12", "13", "14", "15", "latest" ]
    
    services:
      postgres:
        image: postgres:${{ matrix.postgres-version }}
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET ${{ matrix.dotnet-version }}.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}.x
    - name: Restore dependencies
      run: dotnet restore src/$CS_PROJECT.sln
    - name: Build
      run: dotnet build src/$CS_PROJECT.sln --no-restore
    - name: Test ${{ matrix.dotnet-version }} against PostgreSQL ${{ matrix.postgres-version }}
      run: dotnet run --project src/$CS_PROJECT.Tests/$CS_PROJECT.Tests.fsproj -f net${{ matrix.dotnet-version }}
  publish:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: "8.0"
    - name: Package F# Library
      run: dotnet pack src/$FS_PROJECT/$FS_PROJECT.fsproj -c Release
    - name: Move F# package
      run: cp src/$FS_PROJECT/bin/Release/$FS_PROJECT.*.nupkg .
#    - name: Save F# Package
#      uses: actions/upload-artifact@v3
#      with:
#        name: fsharp-package
#        path: src/$FS_PROJECT/bin/Release/$FS_PROJECT.*.nupkg
    - name: Package C# Library
      run: dotnet pack src/$CS_PROJECT/$CS_PROJECT.fsproj -c Release
    - name: Move C# package
      run: cp src/$CS_PROJECT/bin/Release/$CS_PROJECT.*.nupkg .
#    - name: Save C# Package
#      uses: actions/upload-artifact@v3
#      with:
#        name: fsharp-package
#        path: src/$CS_PROJECT/bin/Release/$CS_PROJECT.*.nupkg
    - name: Save Packages
      uses: actions/upload-artifact@v3
      with:
        name: packages
        path: |
          *.nupkg
